site_name: Monkey Docs
  #nav:
  #- Home: index.md
  #- About: about.md
  #- Docker Containers:
  #    - Overview: docker-containers.md
  #    - Adguard: adguard.md
      # Additional Docker container pages...
      #- Networking:
      #    - Overview: networking-overview.md
      #     - GlusterFS: glusterfs.md
  # Additional sections...

theme:
  name: material
  logo: assets/logo6.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlights
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        #icon: material/toggle-switch-off-outline
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        #icon: material/toggle-switch
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  # Additional Markdown extensions...
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  # More pymdownx extensions...

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lp182501
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/leovdpauw
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leovdp73
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/leo-vanderpauw/
  analytics:
    provider: google
    property: G-1XXXXXX

copyright: |
  &copy; 2024 <a href="https://github.com/lp182501" target="_blank" rel="noopener">Leo van der Pauw</a>
