# Project information
site_name: Monkey Docs
site_url: https://docs.networkmonkey.io/
site_author: Leo van der Pauw
theme:
  name: material
  logo: assets/logo6.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    # - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.tooltips
    - navigation.foot
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlights
    - search.share
    - search.suggest
    #- toc.integrate 
    - toc.follow


  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        #icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        #icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: lime

# MD extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
    #  auto_append:
    #    - includes/mkdocs.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Extra config
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lp182501
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/leovdpauw
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leovdp73
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/leo-vanderpauw/
  analytics:
    provider: google
    property: G-1XXXXXX

# Page navigation
nav:
  - Home: index.md
  - Getting started:
    - Installation: page4.md
    - Homelab:
        - homelab/index.md
        - "Hypervisors": 
          - homelab/hypervisors/page1.md
          - homelab/hypervisors/page2.md

# Don't think I really need this...
copyright: |
  &copy; 2024 <a href="https://github.com/lp182501" target="_blank" rel="noopener">Leo van der Pauw</a>
